### ISSUE TITLE
Cameras exported when option is disabled.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#129]

**Comment by UX3D-nopper** [comment]
Fixed here https://github.com/KhronosGroup/glTF-Blender-IO/commit/129cd9c1efa6456ef12b202b3414129ace30a68b

**Comment by julienduroure** [comment]
Is now merged with blender 2.8 repo

**Comment by Moguri** [comment]
I am still seeing this issue in Blender 2.80 RC2 with the attached file (created with Blender 2.79).
[disable_camera.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3439490/disable_camera.zip)

**Comment by julienduroure** [comment]
I can reproduce.
@Moguri , do you mean that camera is always exported (with camera data), or that an empty node is exported when "export camera" is unchecked. In that case, this is related to enhancement #183

**Comment by Moguri** [comment]
I got camera data. My importer was crashing because I forgot to make some fields optional.

It may be a combination of settings. I'll try again to reproduce it.
