### ISSUE TITLE
Exporter always exporting every armature present in the blend file

### ISSUE THREAD

**Issue by Master-J** [KhronosGroup/glTF-Blender-IO#1298]
**Describe the bug**

I'm currently working on a blend file containing multiple rigged assets. When ready, each assets then gets exported using the GLTF exporter.

I noticed that when they get imported, the exported asset contains the expected output plus a  "dummy" armature for each armature present in the blend file. This also happens whether or not "selection only" is enabled in the export settings.

A blend file containing multiple rigged meshes 

**To Reproduce**
1. Create a blend file containing several armatures and rigged meshes
![image](https://user-images.githubusercontent.com/54776415/102532905-f853fc80-40a4-11eb-955a-6e8f6addce6d.png)

2. Export one of the rigged meshes using the gltf exporter (i tried multiple settings combination and all of them gave the same behaviour)
![image](https://user-images.githubusercontent.com/54776415/102533091-39e4a780-40a5-11eb-9679-6852ff816ef3.png)
![image](https://user-images.githubusercontent.com/54776415/102533179-5da7ed80-40a5-11eb-990d-d81a9b2a89ae.png)

3. Import the resulting file somewhere (here in the Godot game engine)
![image](https://user-images.githubusercontent.com/54776415/102533444-b9727680-40a5-11eb-84ad-2762e27042d2.png)

The object is imported correctly and the skinning is also right, but it also contains the other armatures that were in the blend file.

4. Import the file back in Blender using the GLTF importer to check if it's not a bug on the game engine's side
![image](https://user-images.githubusercontent.com/54776415/102533715-11a97880-40a6-11eb-90c8-d84eaabace35.png)

The imported file clearly contains "dummy" armatures made of empties.

**Expected behavior**
The exporter should only export the selected armatures when "selection only" is enabled. In its current state, it exports more data than it should.

**Screenshots**
(see the reproduction steps)

**.blend file/ .gltf**
[demo_file.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5711745/demo_file.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.91

**Comment by scurest** [comment]
This is known, https://github.com/KhronosGroup/glTF-Blender-IO/pull/1126#issuecomment-659912661. Theoretically should be fixed as part of #1244.

**Comment by eugene2k** [comment]
I'm experiencing the same problem in blender 2.93

**Comment by schroef** [comment]
Still present, the selection only only checks for meshes, there is not check for armatures and all are exported. Pretty easy fix/add in the code i guess
