### ISSUE TITLE
Bone positions distorted for animations that are not selected

### ISSUE THREAD

**Issue by viridia** [KhronosGroup/glTF-Blender-IO#1539]
**Describe the bug**

When I export my character to .gltf, the animations produce a warped / distorted pose - but only for animations that were not selected in the action editor at the moment of export. Whichever action is currently selected exports correctly, but actions which are not selected are incorrect.

I have tried viewing the result in different GLTF viewers (including writing my own) and I see the same result.

**To Reproduce**

1. Open the attached blend file
2. Select 'CombatStanceAction' in the action editor
3. Export to .glb
4. Now, view the 'DefaultAction' in any GLTF viewer.

Alternatively, select 'DefaultAction' in blender, and then view 'CombatStanceAction' in the viewer.

**Expected behavior**

Animations exported to GLTF should not be affected by which action is currently selected.

**Screenshots**

A disorted pose:

<img width="358" alt="Screen Shot 2022-01-16 at 11 54 43 AM" src="https://user-images.githubusercontent.com/1166135/149736577-53449ccc-0877-45bb-b474-af7c238c6eb6.png">

The exact same post, but exported when it was selected:

<img width="305" alt="Screen Shot 2022-01-16 at 12 09 49 PM" src="https://user-images.githubusercontent.com/1166135/149736662-47c9413d-2d3f-45bd-9ef4-891a87d77429.png">

**.blend file/ .gltf**

[humanoid-female.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7880385/humanoid-female.blend.zip)

**Version**
 - OS: macOS
 - Blender Version 3.0

**Comment by viridia** [comment]
Just a follow-up on this: I tried reverting to a previous version of Blender in order to see if the bug is recent - unfortunately, loading a file into Blender 2.9 which has been saved in Blender 3.0 has problems - when I export to GLTF, none of the animations come out.

This has pretty much ground my animation workflow to a halt, since I can't seem to find a workaround that will let me export GTLFs.

**Comment by viridia** [comment]
This is still happening in Blender 3.0.1.

Here's an updated version of the scene, I've removed all external links to make debugging easier. Also uploading a gltf file which exhibits the problem.

[gltf-bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7966759/gltf-bug.zip)

**Comment by julienduroure** [comment]
Hello,
Thanks for the report. I will have a look soon

**Comment by julienduroure** [comment]
Linked to #1563 
Tested with #1378 + #1563 --> OK

**Comment by viridia** [comment]
Hi, I downloaded the version linked here https://builder.blender.org/download/experimental/gltf_vtree/ - I did not see any difference in the exported files, I'm sure I must be doing something wrong or downloaded the wrong link.

**Comment by viridia** [comment]
I was also able to get the exporter to crash (python exception KeyError) when attempting to export one of my older blend files, I'll try and upload an example later today.

**Comment by viridia** [comment]
[characters.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8036788/characters.zip)

If you download the attached zip file, open "humanoid-male.blend" and attempt to export to GLTF you'll get a Python exception. This is with the version of Blender I downloaded from the link - Version 3.2.0 (3.2.0 2022-02-09)

**Comment by julienduroure** [comment]
> Hi, I downloaded the version linked here https://builder.blender.org/download/experimental/gltf_vtree/ - I did not see any difference in the exported files, I'm sure I must be doing something wrong or downloaded the wrong link.

The link contains #1378 but not yet #1563

**Comment by julienduroure** [comment]
> If you download the attached zip file, open "humanoid-male.blend" and attempt to export to GLTF you'll get a Python exception. This is with the version of Blender I downloaded from the link - Version 3.2.0 (3.2.0 2022-02-09)

I confirm. Thanks for the use case. I will have a look

**Comment by julienduroure** [comment]
Found the bug :
Seems library override of armature that is hidden is not retrieve in list of object.
Workaround for now : Display your armature before export.

I will check with blender developer if this behavior is a bug or not

**Comment by julienduroure** [comment]
> If you download the attached zip file, open "humanoid-male.blend" and attempt to export to GLTF you'll get a Python exception. This is with the version of Blender I downloaded from the link - Version 3.2.0 (3.2.0 2022-02-09)

This case is fixed now. I was not using the right eval object list. A new build will be available in next few hours, compilation in progress

**Comment by viridia** [comment]
Do you have an updated build link? I'd like to confirm that this has been fixed.

**Comment by julienduroure** [comment]
Yes, here : https://builder.blender.org/download/experimental/gltf_vtree/

Be sure to uncheck "optimize animation size"

**Comment by julienduroure** [comment]
Yes, please open the Animation panel. 
It has a chechbox, but can be expended too. (See the little triangle)

**Comment by viridia** [comment]
OK, I see - that UI is a bit confusing, I've never seen a control that was both a checkbox and a disclosure triangle.

When I uncheck the "optimize animations" option, I get the following:

<img width="1135" alt="export-exception" src="https://user-images.githubusercontent.com/1166135/155870000-8bac4cc2-76ba-4c2a-a469-8e7e08826364.png">

**Comment by julienduroure** [comment]
I see, will be fixed tomorrow. Thanks for reporting.

About size of column: this is not managed by this exporter, but by core blender. Please report it directly on Blender bug tracker.

**Comment by julienduroure** [comment]
Merge issue is now fixed.
A builder issue prevent me to create a new blender build for now. But merging into master (3.2 alpha) should happen tomorrow.
Official blender alpha build will be available Wednesday or Thursday

**Comment by viridia** [comment]
I just downloaded the latest build from the https://builder.blender.org/download/experimental/gltf_vtree/ link - still getting the 'too many values to unpack' error.

**Comment by viridia** [comment]
No, I'm using Mac.

**Comment by viridia** [comment]
Ah, it looks like the date for the intel mac build is also Feb 22.

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Comment by viridia** [comment]
I just download the latest alpha and it appears to be working. So I can start generating art again :)
