### ISSUE TITLE
Exporter, does not save Emissive Factor/Emission Strength Value for materials.

### ISSUE THREAD

**Issue by xylr117z4** [KhronosGroup/glTF-Blender-IO#367]
Currently the Emissive Factor/Emission Strength is not exported to the .glb file.

-------
Steps to Reproduce:

Following this [example](https://docs.blender.org/manual/en/2.80/_images/addons_io-gltf2_material-emissive.png)

I set up a material using the Principal BSDF and Emission nodes.  I then make some adjustments to the Principal and Emission settings to get something looking like [this scene.](https://i.imgur.com/5Az9fEl.png) 

The nodes on each material [look like this.](https://i.imgur.com/39s8mNc.png)

After exporting an re-importing I get this. [imported nodes](https://i.imgur.com/7qaPrMR.png)

I wasn't sure if it was the import process or the export process so I checked the .glb embedded file.  It appears the emissiveFactor portion is always being saved as 1, 1, 1 (see below)

```
"emissiveFactor" : [
                1,
                1,
                1
            ]
```

Knowing that the Emissive Factor is supposed to be an RGB value I also tried attaching an RGB node and attaching it to the strength of the Emission node, however it was still not saved.

-------
Additional Notes:

I also went in and edited the "emissiveFactor" in the embedded .glb file.  Like so...
```
"emissiveFactor" : [
                0.33,
                0.33,
                0.33
            ]
```
When importing this edited file, I get a node tree [including a multiply node.](https://i.imgur.com/MfHIGt1.png) Where the Color2 of the multiply node matched my edited .glb file.  

The result looks okay, but is too bright since it still takes into account the emission node's strength.  (Which is always set to 1.0)

Upon exporting this new scene the emissiveFactor is still not saved.

-----
Using Blender 2.8 Beta Windows 64 bit, March 18th, 19:10:14 build.

Edit: updated example link

**Comment by AlbertoElias** [comment]
Noticed this as well

**Comment by Taroslord** [comment]
I've plugged an emission PNG texture into the Emission slot of a Principled BSDF material, but it will not be exported to glb, too.

Any news about this issue, please?

**Comment by donmccurdy** [comment]
@Taroslord that was fixed in https://github.com/KhronosGroup/glTF-Blender-IO/pull/934. I'm not sure if that's in the most recent Blender releases yet. If not, you could also install the addon from GitHub.

**Comment by scurest** [comment]
This is not fixed. #934 didn't change the exporter at all.

An Image Texture node plugged into the Emission socket on the Principled node should works (since #740). But the emissiveFactor is still always [1,1,1].

**Comment by donmccurdy** [comment]
My mistake! But still, the issue @Taroslord mentions was fixed. While, as you said, the OP's issue has not been fixed.

**Comment by Taroslord** [comment]
I've read the manual and tested it:
1. What works: Plugging an emission texture like it is described in the manual (2.82). You have to use the emission shader workaround (For me it's a workaround and not logic). Link to the manual: https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html
2. What doesn't work: Plugging a texture directly into the emission slot of a BSDF-Shader. It will not be exported, but it should. Because all other textures, that are plugged into the BDSF-shader will be exported, like metallic, roughness or normalmaps. Like described here: https://github.com/KhronosGroup/glTF-Blender-IO/pull/740

**Comment by donmccurdy** [comment]
@Taroslord please [create a new issue](https://github.com/KhronosGroup/glTF-Blender-IO/issues/new?assignees=&labels=&template=bug_report.md&title=) — this one is not about emission textures. We have already implemented support for plugging an Emission texture into Principled BSDF. I just tested it and it's working here, so your problem likely has to do with your version of Blender or with the file, and other details that we ask for in the form when submitting a new bug report.

**Comment by scurest** [comment]
For emissive factor from a MULTIPLY node, see #1155.

About strength:

There's talk about adding an emissive strength input to the Principled node, see [D4971](https://developer.blender.org/D4971) and [discussion about addons being updated](https://blender.community/c/rightclickselect/0cgbbc/).

I believe strength is just a scalar multiplier to the emissive color? So all we need to do is multiply emissiveFactor by it (and clamp)?

**Comment by Taroslord** [comment]
Thank you for your answers. The only way to export emission textures from Blender to glb is to use the official way, that is described in this image and is found in the manual:
https://docs.blender.org/manual/en/2.80/_images/addons_io-gltf2_material-emissive.png

It works, but the problem of this solution: It doesn't support the emission slot inside the principled shader node in Blender. This would be a clean solution in my point of view.

**Comment by emackey** [comment]
@Taroslord, re: Principled BSDF. You're looking at the manual for 2.80.  Check the [manual for 2.90](https://docs.blender.org/manual/en/2.90/addons/import_export/scene_gltf2.html#emissive) instead.  It doesn't show a picture, but the first sentence says it should work with the Principled BSDF node.
