### ISSUE TITLE
exporter unecessarily splits geometry in blocks of 65535 vertices

### ISSUE THREAD

**Issue by aguaviva** [KhronosGroup/glTF-Blender-IO#777]
**Describe the bug**
Tried to export a huge scene, the exporter is splitting unnecessarily the vertex buffers in blocks of a max of 65535 vertices

>12:00:01 | DEBUG: Adding primitive with splitting. Indices: 123480 Vertices: 65535
>12:00:01 | DEBUG: Adding primitive with splitting. Indices: 210033 Vertices: 65534
>12:00:02 | DEBUG: Adding primitive with splitting. Indices: 292386 Vertices: 65533
>12:00:02 | DEBUG: Adding primitive with splitting. Indices: 160830 Vertices: 39829

this was caused by this code

```
        # NOTE: Values used by some graphics APIs as "primitive restart" values are disallowed.
        # Specifically, the value 65535 (in UINT16) cannot be used as a vertex index.
        # https://github.com/KhronosGroup/glTF/issues/1142
        # https://github.com/KhronosGroup/glTF/pull/1476/files

        range_indices = 65535
```
The index that marks a primitive restart is 65535, but that is only true when you are using triangle strips and 16bits index buffers. For other instances, like in my case where we are exporting triangle lists and 32 bit index buffers this doesn't apply. Actually I made that value bigger and the scene exported and loaded fine.

>12:05:48 | INFO: Starting glTF 2.0 export
>12:05:48 | INFO: Extracting primitive: Mesh_0
>12:06:04 | DEBUG: material_idx 0
>12:06:04 | DEBUG: Adding primitive without splitting. Indices: 786801 Vertices: 236431
>12:06:04 | INFO: Primitives created: 1
>12:06:06 | INFO: Finished glTF 2.0 export in 17.52252435684204 s

**To Reproduce**
Just generate a huge sphere and export it, notice the many primitive nodes

**Expected behavior**
I'd expect just a big vertex buffer

**Version**
2.80

**Comment by Vinc3r** [comment]
I'm not quite sure but it seems this comes from the glTF specifications: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#primitiveindices

**Comment by scurest** [comment]
This was #233. It has been fixed in master, so just upgrade to the latest version.

**Comment by julienduroure** [comment]
Yes, please test again with 2.81 beta, this should be fixed

**Comment by tomm1996** [comment]
I can still reproduce with gltf-export from blender 2.81 when viewed in https://sandbox.babylonjs.com/.
GLTF-Export splits the Object at 65534, puts the remaining vertices into another mesh named meshname_primitive1 and puts it into a group named after the mesh.

![image](https://user-images.githubusercontent.com/4152001/69820120-b12c6c80-1200-11ea-86a3-1f8563fb6fda.png)

**Comment by julienduroure** [comment]
@tomm1996 
Sorry, I did a mistake on branch it was solved. 2.81 still split at 65534, but it should be ok in blender 2.82 alpha (you can test downloading it here : builder.blender.org )

**Comment by tomm1996** [comment]
Thank you for solving this <3

**Comment by marquizzo** [comment]
Can confirm, the new exporter that ships with Blender 2.82 solves this problem. Now that 2.82 is the latest stable version, it can be found in the standard [downloads page](https://www.blender.org/download/).

**Comment by alparslanahmed** [comment]
I have the same issue with Blender version 2.92 and last version of exporter!

**Comment by julienduroure** [comment]
@alparslanahmed can you please share your .blend file?

**Comment by alparslanahmed** [comment]
> @alparslanahmed can you please share your .blend file?

Here my .blend file: [https://gofile.io/d/rj6FdY](https://gofile.io/d/rj6FdY)

**Comment by alparslanahmed** [comment]
Can anybody help please?

**Comment by julienduroure** [comment]
I can't reproduce.
Every object is split in 2 because there are 2 different materials.
I can't see any split because of vertices count
