### ISSUE TITLE
Always Sample Animations Problem

### ISSUE THREAD

**Issue by Geegrafix** [KhronosGroup/glTF-Blender-IO#842]
**Describe the bug**
When exporting using "Always Sample Animations" checked on, the keyframes are linear even though the keyframes are set as constant in blender. This causes a problem in viewers since depending on the frame rate, it will always produce tweens. This causes very strange behavior in the viewers if you are wanting and expecting stepped or constant frames to appear.

**To Reproduce**
1. Create a plane
2. Set frame range to 1-15
3. Set a key for scale of 1 on plane at frame 8
4. Set a key for scale of 0 on plane at frame 9
5. Set a key for scale of 1 on plane at frame 10
6. Select all keys and set them to constant
7. Export as glb/gltf with "Always Sample Animations" checked on
8. Drag the glb/gltf into viewer here: https://gltf-viewer.donmccurdy.com/
9. To see it better, use the controls to make animation speed .1

**Expected behavior**
The plane should snap from scale 1 to scale 0 since the keys in blender are constant. Since they are created as linear, you will see the scales are not either 1 or 0, but have in betweens such as .5

[scalePlane.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4005799/scalePlane.zip)

**Comment by julienduroure** [comment]
Confirmed that interpolation can be seen if we change the animation speed.
Currently interpolation is set to LINEAR when animations are sampled, whatever the blender interpolation is. I will add a check to set to STEP when animation is sampled and blender interpolation is constant

**Comment by emackey** [comment]
Fixed in #844

**Comment by oallouch** [comment]
Hi,

I'm quite new to Blender, but I've faced this issue.
I've put some constant keyframes, but I still see linear animations.
I have tried to check/uncheck the "Always Sample Animations" parameter, without success.
![image](https://user-images.githubusercontent.com/2777369/123526043-91f40a80-d6d5-11eb-8042-784898924dd0.png)

Thx in advance,

Olivier
