### ISSUE TITLE
Issue with animations after fix skinning patch

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#862]
**Describe the bug**

Based on:

https://github.com/KhronosGroup/glTF-Blender-IO/pull/857

This plays correctly in vscodium's three.js.

@scurest 

**To Reproduce**
1. Go to Blender
2. Click on import gltf
3. Scroll down to play action and one of the 5 "Damage_heavy" animations
4. Nothing plays.

**Expected behavior**

Animations should play

**Screenshots**

![all_5_robot_motion](https://user-images.githubusercontent.com/32321/71949392-34d66300-3188-11ea-809c-4fb98b30173f.PNG)

https://drive.google.com/drive/folders/1iDPpCvarbw7_n8gpGCzkXvkSJLTRl_eK

Has videos and source files.

**Version**
 - OS: Windows
 - Blender Version 2.81 + https://github.com/scurest/glTF-Blender-IO/commit/8bc87fc8b8cd77fd5c8c8e9adb3d0a7b31c8655d + https://github.com/KhronosGroup/glTF-Blender-IO/issues/858

**Additional context**

Great work @scurest for making Blender awesome.

**Comment by scurest** [comment]
Thanks for continuing to check things fire.

I _think_ this is fixed, can you check? It's related to the fact that it would make two `Damage_heavy` actions (it should only make one), but I'm not really sure why that would cause it to decide the pose bone curves were invalid.

**Comment by fire** [comment]
The white robot's skeleton flickers, but the red robots still don't move.

Referencing:

https://github.com/scurest/glTF-Blender-IO/commit/ce00a220ed00b2d0af8ab58d170f48a92a691fb0

**Comment by scurest** [comment]
Really? If I select the object `Armature` and the action `Walk-cycle_Armature` it definitely walks forward.

![robo](https://user-images.githubusercontent.com/11024420/71954947-7547d800-31ac-11ea-93eb-20e4d21ddc3d.png)

**Comment by fire** [comment]
Damage_heavy_Armature works too, but not 2, 3, 4, 5.

**Comment by fire** [comment]
If you want, I can reduce the scene to two red robots.

**Comment by scurest** [comment]
If I select `Armature 3` and the action `Damage_heavy 3_Armature 3`, it plays for me.

**Comment by fire** [comment]
Wow, I found a UI bug when how armature works in the interface..

Not even sure where to begin. Why does the armature need to be selected to play an an action?

**Comment by fire** [comment]
That said the animation does appear to be in blender.

**Comment by scurest** [comment]
It doesn't have to be selected, but you have to manually assign the action you want to play on each object. The importer will set things up so the first animation in the file is "playing" but there's no good way to play any other. See #840.

**Comment by fire** [comment]
Not sure how to fix that.

**Comment by fire** [comment]
@scurest I would at least set the first action to one that CAN be played by the object.

**Comment by scurest** [comment]
No, because that would create an "animation" that doesn't actually exist in the file. You'd essentially be picking random pieces of different animations and sticking them together, which is nonsense. That used to happen, see #671.

**Comment by scurest** [comment]
It's hacky, but I use [this script](https://gist.github.com/scurest/ed3d80213fcf422bf4314eb4f9f514c6) to set an animation as a workaround for having no proper way. Put it in the text editor, fill in the `anim_name` variable to the NLA track name, and hit "Run Script".

Btw, thanks for catching this bug :) If you find any more, let me know!

**Comment by julienduroure** [comment]
Hello,
If I understand correctly, there is no issue here.
Anyway, we will avoid open tickets on feature not yet merged. Let's the discussion continue on the patch itself if there are some issues.
